title: Learning Python in github
author: Hosseines
email: hossein.eskandaripour@outlook.com
description: > # this means to ignore newlines until "baseurl:"
   Learning Python will help me to use it in my PhD dessertation

# social links

github_username:  Hosseineskandaripour
show_excerpts: true # set to false to remove excerpts on the homepage
them: minima
