title: Learn Python in GitHub
author: Hossein Esakandaripour
email: hossein.eskandaripour@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I would like to learn and code with Python and use my knowledge in my PhD dissertation
  Therefore, I started to work with github. I think practice coding is an ideal way to learn it 

# social links

github_username:  Hosseineskandaripour

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
